/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  cols,
} from './components/column/column.cols';
import {
  level,
} from './components/title/title.size';


export namespace Components {

  interface QGridColumn {
    /**
    * Defines general column size
    */
    'size': cols | undefined;
    /**
    * Defines large column size
    */
    'sizeLg': cols | undefined;
    /**
    * Defines medium column size
    */
    'sizeMd': cols | undefined;
    /**
    * Defines small column size
    */
    'sizeSm': cols | undefined;
    /**
    * Defines extra small column size
    */
    'sizeXs': cols | undefined;
  }
  interface QGridColumnAttributes extends StencilHTMLAttributes {
    /**
    * Defines general column size
    */
    'size'?: cols | undefined;
    /**
    * Defines large column size
    */
    'sizeLg'?: cols | undefined;
    /**
    * Defines medium column size
    */
    'sizeMd'?: cols | undefined;
    /**
    * Defines small column size
    */
    'sizeSm'?: cols | undefined;
    /**
    * Defines extra small column size
    */
    'sizeXs'?: cols | undefined;
  }

  interface QGrid {}
  interface QGridAttributes extends StencilHTMLAttributes {}

  interface QTitle {
    /**
    * Defines general column size
    */
    'level': level;
  }
  interface QTitleAttributes extends StencilHTMLAttributes {
    /**
    * Defines general column size
    */
    'level'?: level;
  }
}

declare global {
  interface StencilElementInterfaces {
    'QGridColumn': Components.QGridColumn;
    'QGrid': Components.QGrid;
    'QTitle': Components.QTitle;
  }

  interface StencilIntrinsicElements {
    'q-grid-column': Components.QGridColumnAttributes;
    'q-grid': Components.QGridAttributes;
    'q-title': Components.QTitleAttributes;
  }


  interface HTMLQGridColumnElement extends Components.QGridColumn, HTMLStencilElement {}
  var HTMLQGridColumnElement: {
    prototype: HTMLQGridColumnElement;
    new (): HTMLQGridColumnElement;
  };

  interface HTMLQGridElement extends Components.QGrid, HTMLStencilElement {}
  var HTMLQGridElement: {
    prototype: HTMLQGridElement;
    new (): HTMLQGridElement;
  };

  interface HTMLQTitleElement extends Components.QTitle, HTMLStencilElement {}
  var HTMLQTitleElement: {
    prototype: HTMLQTitleElement;
    new (): HTMLQTitleElement;
  };

  interface HTMLElementTagNameMap {
    'q-grid-column': HTMLQGridColumnElement
    'q-grid': HTMLQGridElement
    'q-title': HTMLQTitleElement
  }

  interface ElementTagNameMap {
    'q-grid-column': HTMLQGridColumnElement;
    'q-grid': HTMLQGridElement;
    'q-title': HTMLQTitleElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
