/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';
import {
  level,
} from './components/title/title.level';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface QTitle {
    /**
    * Defines general column size
    */
    'level': level;
  }
  interface QTitle {
    /**
    * Defines general column size
    */
    'level': level;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface MyComponent extends JSXBase.HTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface QTitle extends JSXBase.HTMLAttributes {
    /**
    * Defines general column size
    */
    'level'?: level;
  }
  interface QTitle extends JSXBase.HTMLAttributes {
    /**
    * Defines general column size
    */
    'level'?: level;
  }

  interface ElementInterfaces {
    'MyComponent': Components.MyComponent;
    'MyComponent': Components.MyComponent;
    'QTitle': Components.QTitle;
    'QTitle': Components.QTitle;
  }

  interface IntrinsicElements {
    'MyComponent': LocalJSX.MyComponent;
    'MyComponent': LocalJSX.MyComponent;
    'QTitle': LocalJSX.QTitle;
    'QTitle': LocalJSX.QTitle;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLQTitleElement extends Components.QTitle, HTMLStencilElement {}
  var HTMLQTitleElement: {
    prototype: HTMLQTitleElement;
    new (): HTMLQTitleElement;
  };

  interface HTMLQTitleElement extends Components.QTitle, HTMLStencilElement {}
  var HTMLQTitleElement: {
    prototype: HTMLQTitleElement;
    new (): HTMLQTitleElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'my-component': HTMLMyComponentElement
    'q-title': HTMLQTitleElement
    'q-title': HTMLQTitleElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'my-component': HTMLMyComponentElement;
    'q-title': HTMLQTitleElement;
    'q-title': HTMLQTitleElement;
  }
}

